FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /main

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /tmp

ENV TZ="Europe/Berlin"
ENV USERNAME="YOUR_USERNAME_GOES_HERE"
ENV PASSWORD="YOUR_PASSWORD_GOES_HERE"

ENV INFOWATCH_URL="YOUR_INFOWATCH_URL_GOES_HERE"
ENV INFOWATCH_REV_PROXY_USERNAME="YOUR_INFOWATCH_REV_PROXY_USERNAME_GOES_HERE"
ENV INFOWATCH_REV_PROXY_PASSWORD="YOUR_INFOWATCH_REV_PROXY_PASSWORD_GOES_HERE"
ENV INFOWATCH_PID="YOUR_INFOWATCH_PID_GOES_HERE"

ENV ELASTIC_SEARCH_URL="YOUR_ELASTIC_SEARCH_URL_GOES_HERE"
ENV ELASTIC_SEARCH_USERNAME="YOUR_ELASTIC_SEARCH_USERNAME_GOES_HERE"
ENV ELASTIC_SEARCH_PASSWORD="YOUR_INFOWATCH_ELASTIC_SEARCH_PASSWORD_GOES_HERE"
ENV ELASTIC_SEARCH_PID="YOUR_ELASTIC_SEARCH_PID_GOES_HERE"

COPY --from=build /main /webdav

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/webdav"]